name: docker-image

on:
  push:  
    branches: [ "dockerimage" ] # Cuando haya un push a la rama "refactor-microservicio-ingematica" se ejecuta el codigo
  pull_request:
    types:
    - closed
    branches:
    - 'dockerimage'
jobs:
   build_test: # Este es el identificador único del job
    name: "Build backend"  # Nombre descriptivo para mostrar en los logs
    if: github.event.pull_request.merged == true  # Este job solo se ejecutará si el PR ha sido fusionado
    runs-on: ubuntu-latest  # Ejecutar en una máquina virtual con Ubuntu

    strategy:
      matrix:
        node-version: [16.x]  # Especificamos que el job se debe ejecutar con Node.js 16.x


    steps:
    - uses: actions/checkout@v4 # Esto se ejecuta en la VM, aca descargamos el código de 'refactor-microservicio-ingematica'
    - name: setup node
      uses: actions/setup-node@master
      with:
          node-version: ${{ matrix.node-version }}
   # install applicaion dependencies
    - name: Install dependencies
      run: |
          npm install
          npm ci
      # build and test the apps     
    - name: Build and Test
      run: |
        npm run build  # Comando para construir la aplicación (ajustar según sea necesario)


   docker:
     needs: build_test
     runs-on: ubuntu-latest
     steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: halier/appEventosBackend-Clean-Architecture:latest
